# Site settings
title: "The Owlery"
email: "chasem000@gmail.com"
description: "A hyperlink odyssey."
url: "http://chasemccoy2.github.io"

# Build settings
markdown: kramdown
highlighter: pygments

excerpt_separator: "\n\n"

permalink: /:year/:month/:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: post
  -
    scope:
      path: "asides"
      type: "posts"
    values:
      category: asides
  -
    scope:
      path: "columns"
      type: "posts"
    values:
      category: columns
  -
    scope:
      path: "quotes"
      type: "posts"
    values:
      category: quotes
