# Site settings
title: "The Owlery"
email: "chasem000@gmail.com"
description: "A hyperlink odyssey."
url: "http://theowlery.co"

# Build settings
markdown: kramdown
highlighter: rouge
future: true

excerpt_separator: "\n\n"

permalink: /:year/:month/:title
