# Site settings
title: "The Owlery"
email: "chasem000@gmail.com"
description: "A hyperlink odyssey."
url: "http://chasemccoy2.github.io"
permalink: /:year/:month/:title.html
timezone: America/New_York

# Build settings
markdown: kramdown

highlighter: pygments
excerpt_separator: "\n\n"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: post
  -
    scope:
      path: "asides"
      type: "posts"
    values:
      category: asides
  -
    scope:
      path: "columns"
      type: "posts"
    values:
      category: columns


jekyll-archives:
  enabled: [year, month, day]
  layout: 'default'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
