# Permalinks
permalink: /:title
permalink: pretty

# Setup
title: Chase McCoy
url: http://getpoole.com

sass:
  sass_dir: _sass
  style: :compressed

collections:
  - books
  - chicago
  - music
  - design
