# Site settings
title: "Chase McCoy "
email: "chasem000@gmail.com"
description: "Description"
url: "Site URL"

# Build settings
markdown: kramdown
highlighter: rouge

permalink: /:year/:month/:title

collections:
  portfolio:
    output: false
  timeline:
    output: false
