# Site settings
title: "The Owlery"
email: "chasem000@gmail.com"
description: "Liberal arts, in your browser."
url: "http://audaciousfox.com" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title.html
timezone: America/New_York

# Build settings
markdown: kramdown

highlighter: pygments
excerpt_separator: "<!-- more -->"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: post
  -
    scope:
      path: "asides"
      type: "posts"
    values:
      category: asides
  -
    scope:
      path: "columns"
      type: "posts"
    values:
      category: columns


jekyll-archives:
  enabled: [year, month, day]
  layout: 'default' #'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
